--查询
select * from MortgageInfo
where custid = '4'

SELECT * FROM MortgageInfo
where BorrowMoney >= 10000 and CardPassword = '777777'

SELECT * FROM CardInfo
where SaveType = '活期'and LeftMoney >3500

SELECT * 
FROM CARDINFO INNER JOIN MORTGAGEINFO ON CARDINFO.CUSTID = MORTGAGEINFO.CUSTID
WHERE CARDINFO.CUSTID = 1 

--嵌套
SELECT distinct* FROM MORTGAGEINFO
WHERE CUSTID = (SELECT CUSTID FROM ACCOUNTINFO
		WHERE CUSTNAME = '乔布斯')

SELECT CUSTID,AVG(BORROWMONEY) FROM MORTGAGEINFO
GROUP BY CUSTID

SELECT CUSTID AS '客户编号',COUNT(*) AS '贷款账户数量' FROM MORTGAGEINFO
GROUP BY CUSTID